[tool.poetry]
name = "portfolio-management"
version = "0.1.0"
description = "Portfolio management module"
authors = ["Diego Alonso <alonsocandiadiego@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[tool.poetry.group.dev.dependencies]
pytest = "^9.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
